name: Release

on:
  push:
    tags: ["v*"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Create release assets"
      run: |
        set -x
        assets=("-a" "./bash_aliases_auto" "-a" "./bash_aliases")
        bundle_dir="$(mktemp -d)"
        for script in ./*.sh; do
          bash ./bundle-script.sh --gzip --check '--help' "$script" "$bundle_dir/$script" ./lib/parse_args.sh \
            || bash ./bundle-script.sh --gzip --check '--help' "$script" "$bundle_dir/$script" ./lib/parse_args_v2.sh || exit 1
          assets+=("-a" "$bundle_dir/$script")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
